before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb libx11-dev libfreetype6-dev libxft-dev libpng-dev libz-dev libjpeg-dev $([ "$WINDOW_MANAGER" = "kwin" ] && echo -n "kde-window-manager" || echo -n $WINDOW_MANAGER)
 - '[ "$USE_SYSTEM_PERL" = "1" ] && perlbrew off || true'
 - '[ "$USE_SYSTEM_PERL" = "1" ] && sudo apt-get install -qq perl-tk || true'
 - Xvfb :123 &
 - export DISPLAY=:123
 # Wait until X server is available
 - perl -MIO::Socket::INET -e 'for (1..10) { IO::Socket::INET->new(PeerAddr => "localhost:6123") and exit; sleep 1 }'
 - $WINDOW_MANAGER &
 # Wait until window manager is running
 - sleep 2
install:
 # For system perl all dependencies (Tk) are already installed
 # Skipping this step saves some seconds, as the EUMM upgrade
 # is not done.
 - '[ "$USE_SYSTEM_PERL" = "1" ] && true || cpanm --quiet --installdeps --notest .'
language: perl
matrix:
 include:
  - perl: "5.14"
    env: USE_SYSTEM_PERL=1 WINDOW_MANAGER=twm
  - perl: "5.14"
    env: USE_SYSTEM_PERL=1 WINDOW_MANAGER=fvwm
  - perl: "5.14"
    env: USE_SYSTEM_PERL=1 WINDOW_MANAGER=metacity
  - perl: "5.14"
    env: USE_SYSTEM_PERL=1 WINDOW_MANAGER=xfwm4
  - perl: "5.14"
    env: USE_SYSTEM_PERL=1 WINDOW_MANAGER=fluxbox
  - perl: "5.14"
    env: USE_SYSTEM_PERL=1 WINDOW_MANAGER=sawfish
  - perl: "5.14"
    env: USE_SYSTEM_PERL=1 WINDOW_MANAGER=kwin
  - perl: "5.20"
    env: WINDOW_MANAGER=fvwm
  - perl: "5.8"
    env: WINDOW_MANAGER=fvwm
